require "joachimkoch.options"
require "joachimkoch.keymaps"
require "joachimkoch.plugins"
require "joachimkoch.colorscheme"
require "joachimkoch.cmp"
require "joachimkoch.lsp"
require "joachimkoch.telescope"
require "joachimkoch.treesitter"
